### ISSUE TITLE
How do you start your work day?

### ISSUE THREAD

**Issue by sindresorhus** [coderabbi/ama#5]

**Comment by coderabbi** [comment]
So that has changed a bit over the last year as I've done a tremendous amount of conference travelling and have recently begun commuting to NYC (2 hours) a couple days a week, so my old 'routine' really doesn't apply anymore...

I try to start me workday with a code pomodoro as I've found that days for me tend to follow their beginning - if I'm productive first thing in the morning, I'll be productive all day. I try to ensure this by beginning my day the night before - inbox zero, browser tab zero and an action plan for the next day including the focus of that first pomodoro.

**Comment by eonist** [comment]
Browser tab zero!
